
# This file is auto-generated by run_cors_backend.py
# It applies CORS middleware to the FastAPI app on startup

from fastapi.middleware.cors import CORSMiddleware
from backend.app import app

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3005", "http://127.0.0.1:3000", "http://127.0.0.1:3005"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
